kind: Service
apiVersion: v1
metadata:
  name: msa-apireg
spec:
  clusterIP: None
  selector:
    app: msa-apireg
  ports:
  - port: 8761
    name: web
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: apireg
  labels:
    app: apireg
spec:
  serviceName: msa-apireg
  replicas: 2
  selector:
    matchLabels:
      app: msa-apireg
  template:
    metadata:
      labels:
        app: msa-apireg
        version: "1.0.1"
    spec:
      containers:
      - name: apireg
        image: docker.gsp.sicc.co.kr/apireg:1.0.1
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: spring.cloud.config.uri
          value: http://msa-config.development.svc.cluster.local:8888
        - name: eureka.datacenter
          value: GSP Cluster
        - name: eureka.environment
          value: Development Environment
        - name: eureka.client.serviceUrl.defaultZone
          value: http://apireg-0.msa-apireg.development.svc.cluster.local:8761/eureka/,http://apireg-1.msa-apireg.development.svc.cluster.local:8761/eureka/
        ports:
        - name: http
          containerPort: 8761
  podManagementPolicy: Parallel

